add: creating a jump path via menu and console command
yapb/yapb pull request #445
Opened 2023-05-10 19:12 UTC by Vladislav4KZ

Differences from commit by commandcobra7:
If there is already an outgoing or two-way (bidirectional) path from the source node to the destination node, the outgoing path will be removed and an outgoing jump path will be added.

2023-05-10 19:22 UTC, jeefo commented
type 0/1 is meaningless maybe

```
CR_DECLARE_SCOPED_ENUM (PathConnection,
   None = -1,
   Outgoing = 0,
   Incoming,
   Bidirectional
)
```
?

2023-05-12 17:21 UTC, Vladislav4KZ commented
@jeefo check the latest commits.
Is it good now?

2023-05-12 18:10 UTC, jeefo requested changes

2023-05-12 18:10 UTC, jeefo commented on src/graph.cpp
> +         else if (link.index == nodeTo && link.flags & PathFlag::Jump) {
pls: (link.flags & PathFlag::Jump)

2023-05-12 18:15 UTC, Vladislav4KZ commented on src/graph.cpp
> +         else if (link.index == nodeTo && link.flags & PathFlag::Jump) {
Done

2023-05-12 18:16 UTC, jeefo approved these changes

2023-05-12 18:19 UTC, merged